name: Update stdlib-changes

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - uses: cachix/install-nix-action@v23
    - uses: cachix/cachix-action@v12
      with:
        name: emacs-ci
    - run: tools/sym-dump-all
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Regenerate stdlib-changes
        file_pattern: data/stdlib-changes
